### ISSUE TITLE
Can this test tool be used to test non-distributed file systems?

### ISSUE THREAD

**Issue by CMO123** [distributed-system-analysis/smallfile#15]
Can this test tool be used to test non-distributed file systems? like ext4 or btrfs

**Comment by bengland2** [comment]
@CMO123 yes it can, just leave off --host-set, but beware of running on storage with extremely low latency, such as NVDIMM or memory-resident filesystems - python interpreter may not be fast enough, you may have to use pypy.   You can tell if this is happening - look for smallfile threads that are running at/near 100% in "top -H"

**Comment by CMO123** [comment]
thank you very much~~
