### ISSUE TITLE
Control maximum directories that can exist at any given time.

### ISSUE THREAD

**Issue by contactr2m** [distributed-system-analysis/smallfile#16]
How would you restrict maximum directories that can exist any given time ?
It seems logic revolves around maximum files, and if maximum files is 10k-20k then no of directories are way too much. script spends a lot of time in creating those directories first, i would like to restrict maximum dirs. 

Interested in incorporating these options.
dirs_per_dir
maximum_dirs

Any suggestion ?

**Comment by bengland2** [comment]
@contactr2m do you have a log you can attach that shows what happens and what input parameters were?   There is already an option for --files-per-dir and --dirs-per-dir .  The default for files-per-dir is relatively low (100 if I remember right) but you can increase it to 1000 if you want and this will radically reduce number of directories.  There is also an undocumented parameter --min-dirs-per-sec that lets smallfile wait longer for subdirectories to be created.    Subdirectories are created first, before the test starts, so we are measuring file creation time and not directory creation time.  There is a separate "mkdir" operation type to measure directory creation performance.   Let me know if the README.md documentation doesn't cover any of this  or if you have further issues.
