### ISSUE TITLE
Error displaying error message

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/smallfile#18]
The error message "record size cannot exceed file size" is correct and informative but it looks like the usage statement has a slight problem (undefined). 

Traceback (most recent call last):
  File "./smallfile_cli.py", line 284, in <module>
    run_workload()
  File "./smallfile_cli.py", line 265, in run_workload
    params = parse.parse()
  File "/root/smallfile/parse.py", line 192, in parse
    usage('record size cannot exceed file size')
NameError: global name 'usage' is not defined

**Comment by bengland2** [comment]
thx Tim.  Python unfortunately doesn't catch errors like this until
runtime, so unless you can trigger the error condition, you can't detect
the bug.    Will fix it.

**Comment by bengland2** [comment]
@wilkins11 found other similar problems as well because of this, thx.  [pushed fix](https://github.com/distributed-system-analysis/smallfile/commit/d8fab7a13d0a4b6dd01ee4e601b6a4cfb7b762c3) to github
