### ISSUE TITLE
Please create a v1.1 or later release build

### ISSUE THREAD

**Issue by dustinblack** [distributed-system-analysis/smallfile#35]
The smallfile tool is being used version-controlled as a [plugin for Arcaflow](https://github.com/arcalot/arcaflow-plugins/tree/main/python/smallfile). We are currently using the github tag v1.1 to pull the latest release, which we use for the histogram post-processing features. As github tags can be unreliable, we would like to point to a release build instead per https://github.com/arcalot/arcaflow-plugins/issues/22.

Also see related issue #34

**Comment by portante** [comment]
Created https://github.com/distributed-system-analysis/smallfile/releases/tag/1.1.
